# GitHub Actions CI/CD Pipeline for Customer Churn Prediction
#
# This workflow:
# 1. Triggers on push to main branch
# 2. Builds Docker image (validates Dockerfile)
# 3. Does NOT push to any registry (Docker Hub login disabled)
# 4. (Optional) Deploys to cloud (AWS ECS, GCP Cloud Run, etc.)

name: Build and Validate

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

env:
  IMAGE_TAG: telco-churn-app:latest

jobs:
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build Docker image (without pushing)
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE_TAG }}
          load: true

      # Step 4: Output build success
      - name: Output build details
        run: |
          echo "✅ Docker image built successfully: ${{ env.IMAGE_TAG }}"
          docker images | grep telco-churn-app || echo "Image built but not visible in local registry"

  # OPTIONAL: Deploy to AWS ECS
  # Uncomment and configure if deploying to AWS
  # deploy-aws-ecs:
  #   name: Deploy to AWS ECS
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #
  #   steps:
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1
  #
  #     - name: Update ECS service
  #       run: |
  #         aws ecs update-service \
  #           --cluster churn-prediction-cluster \
  #           --service churn-prediction-service \
  #           --force-new-deployment

  # OPTIONAL: Deploy to GCP Cloud Run
  # Uncomment and configure if deploying to GCP
  # deploy-gcp-cloud-run:
  #   name: Deploy to GCP Cloud Run
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #
  #   steps:
  #     - name: Authenticate to Google Cloud
  #       uses: google-github-actions/auth@v1
  #       with:
  #         credentials_json: ${{ secrets.GCP_SA_KEY }}
  #
  #     - name: Deploy to Cloud Run
  #       uses: google-github-actions/deploy-cloudrun@v1
  #       with:
  #         service: churn-prediction-api
  #         image: ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}
  #         region: us-central1
